################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Core/Src/freertos.c \
../Core/Src/main.c \
../Core/Src/stm32l4xx_hal_msp.c \
../Core/Src/stm32l4xx_it.c \
../Core/Src/syscalls.c \
../Core/Src/sysmem.c \
../Core/Src/system_stm32l4xx.c 

OBJS += \
./Core/Src/freertos.o \
./Core/Src/main.o \
./Core/Src/stm32l4xx_hal_msp.o \
./Core/Src/stm32l4xx_it.o \
./Core/Src/syscalls.o \
./Core/Src/sysmem.o \
./Core/Src/system_stm32l4xx.o 

C_DEPS += \
./Core/Src/freertos.d \
./Core/Src/main.d \
./Core/Src/stm32l4xx_hal_msp.d \
./Core/Src/stm32l4xx_it.d \
./Core/Src/syscalls.d \
./Core/Src/sysmem.d \
./Core/Src/system_stm32l4xx.d 


# Each subdirectory must supply rules for building sources it contributes
Core/Src/freertos.o: ../Core/Src/freertos.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/freertos.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/main.o: ../Core/Src/main.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/main.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32l4xx_hal_msp.o: ../Core/Src/stm32l4xx_hal_msp.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32l4xx_hal_msp.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/stm32l4xx_it.o: ../Core/Src/stm32l4xx_it.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/stm32l4xx_it.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/syscalls.o: ../Core/Src/syscalls.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/syscalls.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/sysmem.o: ../Core/Src/sysmem.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/sysmem.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Core/Src/system_stm32l4xx.o: ../Core/Src/system_stm32l4xx.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Core/Src/system_stm32l4xx.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

