################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Drivers/vl53l0x/stm32l475e_iot01.c \
../Drivers/vl53l0x/vl53l0x_api.c \
../Drivers/vl53l0x/vl53l0x_api_calibration.c \
../Drivers/vl53l0x/vl53l0x_api_core.c \
../Drivers/vl53l0x/vl53l0x_api_ranging.c \
../Drivers/vl53l0x/vl53l0x_api_strings.c \
../Drivers/vl53l0x/vl53l0x_platform.c \
../Drivers/vl53l0x/vl53l0x_platform_log.c \
../Drivers/vl53l0x/vl53l0x_proximity.c 

CPP_SRCS += \
../Drivers/vl53l0x/ring_buffer.cpp \
../Drivers/vl53l0x/tof_gestures_DIRSWIPE_1.cpp \
../Drivers/vl53l0x/tof_gestures_SWIPE_1.cpp \
../Drivers/vl53l0x/tof_gestures_TAP_1.cpp \
../Drivers/vl53l0x/tof_motion.cpp 

OBJS += \
./Drivers/vl53l0x/ring_buffer.o \
./Drivers/vl53l0x/stm32l475e_iot01.o \
./Drivers/vl53l0x/tof_gestures_DIRSWIPE_1.o \
./Drivers/vl53l0x/tof_gestures_SWIPE_1.o \
./Drivers/vl53l0x/tof_gestures_TAP_1.o \
./Drivers/vl53l0x/tof_motion.o \
./Drivers/vl53l0x/vl53l0x_api.o \
./Drivers/vl53l0x/vl53l0x_api_calibration.o \
./Drivers/vl53l0x/vl53l0x_api_core.o \
./Drivers/vl53l0x/vl53l0x_api_ranging.o \
./Drivers/vl53l0x/vl53l0x_api_strings.o \
./Drivers/vl53l0x/vl53l0x_platform.o \
./Drivers/vl53l0x/vl53l0x_platform_log.o \
./Drivers/vl53l0x/vl53l0x_proximity.o 

C_DEPS += \
./Drivers/vl53l0x/stm32l475e_iot01.d \
./Drivers/vl53l0x/vl53l0x_api.d \
./Drivers/vl53l0x/vl53l0x_api_calibration.d \
./Drivers/vl53l0x/vl53l0x_api_core.d \
./Drivers/vl53l0x/vl53l0x_api_ranging.d \
./Drivers/vl53l0x/vl53l0x_api_strings.d \
./Drivers/vl53l0x/vl53l0x_platform.d \
./Drivers/vl53l0x/vl53l0x_platform_log.d \
./Drivers/vl53l0x/vl53l0x_proximity.d 

CPP_DEPS += \
./Drivers/vl53l0x/ring_buffer.d \
./Drivers/vl53l0x/tof_gestures_DIRSWIPE_1.d \
./Drivers/vl53l0x/tof_gestures_SWIPE_1.d \
./Drivers/vl53l0x/tof_gestures_TAP_1.d \
./Drivers/vl53l0x/tof_motion.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/vl53l0x/ring_buffer.o: ../Drivers/vl53l0x/ring_buffer.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/ring_buffer.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/stm32l475e_iot01.o: ../Drivers/vl53l0x/stm32l475e_iot01.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/stm32l475e_iot01.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/tof_gestures_DIRSWIPE_1.o: ../Drivers/vl53l0x/tof_gestures_DIRSWIPE_1.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/tof_gestures_DIRSWIPE_1.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/tof_gestures_SWIPE_1.o: ../Drivers/vl53l0x/tof_gestures_SWIPE_1.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/tof_gestures_SWIPE_1.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/tof_gestures_TAP_1.o: ../Drivers/vl53l0x/tof_gestures_TAP_1.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/tof_gestures_TAP_1.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/tof_motion.o: ../Drivers/vl53l0x/tof_motion.cpp
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I../Drivers/CMSIS/Include -I../Core/Inc -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I../Drivers/STM32L4xx_HAL_Driver/Inc -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-use-cxa-atexit -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/tof_motion.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_api.o: ../Drivers/vl53l0x/vl53l0x_api.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_api.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_api_calibration.o: ../Drivers/vl53l0x/vl53l0x_api_calibration.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_api_calibration.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_api_core.o: ../Drivers/vl53l0x/vl53l0x_api_core.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_api_core.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_api_ranging.o: ../Drivers/vl53l0x/vl53l0x_api_ranging.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_api_ranging.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_api_strings.o: ../Drivers/vl53l0x/vl53l0x_api_strings.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_api_strings.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_platform.o: ../Drivers/vl53l0x/vl53l0x_platform.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_platform.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_platform_log.o: ../Drivers/vl53l0x/vl53l0x_platform_log.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_platform_log.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Drivers/vl53l0x/vl53l0x_proximity.o: ../Drivers/vl53l0x/vl53l0x_proximity.c
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DDEBUG -DSTM32L475xx -c -I../Middlewares/Third_Party/FreeRTOS/Source/include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/vl53l0x" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/mx25r6435f" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/Common" -I../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM4F -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/Message" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lis3mdl" -I../Drivers/CMSIS/Include -I../Core/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP" -I../Drivers/CMSIS/Device/ST/STM32L4xx/Include -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lsm6dsl" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components" -I../Drivers/STM32L4xx_HAL_Driver/Inc -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/lps22hb" -I../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/B-L475E-IOT01" -I"C:/Users/claud/STM32CubeIDE/workspace_1.1.0/FireSystem/Drivers/BSP_B-L475E-IOT01-bfe8272ced90/Drivers/BSP/Components/hts221" -I../Drivers/STM32L4xx_HAL_Driver/Inc/Legacy -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Drivers/vl53l0x/vl53l0x_proximity.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

